# Generated by Django 3.0.10 on 2024-01-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPV4_SRC_ADDR', models.GenericIPAddressField()),
                ('L4_SRC_PORT', models.IntegerField()),
                ('IPV4_DST_ADDR', models.GenericIPAddressField()),
                ('L4_DST_PORT', models.IntegerField()),
                ('PROTOCOL', models.IntegerField()),
                ('L7_PROTO', models.FloatField()),
                ('IN_BYTES', models.IntegerField()),
                ('OUT_BYTES', models.IntegerField()),
                ('IN_PKTS', models.IntegerField()),
                ('OUT_PKTS', models.IntegerField()),
                ('TCP_FLAGS', models.IntegerField()),
                ('FLOW_DURATION_MILLISECONDS', models.IntegerField()),
            ],
        ),
    ]
